cache-dir = "./.poetry-cache"
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = true
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
