import os

SCRAPING_POSTGRES_USER = os.environ.get("POSTGRES_SCRAPING_USER", None)
SCRAPING_POSTGRES_PASSWORD = os.environ.get("POSTGRES_SCRAPING_PASSWORD", None)
SCRAPING_POSTGRES_HOST = os.environ.get("POSTGRES_SCRAPING_HOST", None)
SCRAPING_POSTGRES_PORT = os.environ.get("POSTGRES_SCRAPING_PORT", None)

GREEN_DB_POSTGRES_USER = os.environ.get("POSTGRES_GREEN_DB_USER", None)
GREEN_DB_POSTGRES_PASSWORD = os.environ.get("POSTGRES_GREEN_DB_PASSWORD", None)
GREEN_DB_POSTGRES_HOST = os.environ.get("POSTGRES_GREEN_DB_HOST", None)
GREEN_DB_POSTGRES_PORT = os.environ.get("POSTGRES_GREEN_DB_PORT", None)
