import json
from typing import List

from core.domain import ConsumerLifestageType, GenderType, ProductCategory


def combine_results(
    path_2_category: dict,
    gender: str,
    consumer_lifestage: str,
    filters: list = [
        "animal_welfare",
        "fair_conditions",
        "reducing_emissions",
        "reusing_materials",
        "sustainable_beauty",
        "water_saving",
    ],
) -> List[dict]:
    results = []
    for path, info in path_2_category.items():
        category, meta_data = info if type(info) == tuple else (info, {})
        results.append(
            {
                "start_urls": f"https://www.zalando.co.uk/{path}/?cause={'.'.join(filters)}",
                "category": category,
                "gender": gender,
                "consumer_lifestage": consumer_lifestage,
                "meta_data": json.dumps({"family": "FASHION", **meta_data}),
            }
        )
    return results


def male() -> List[dict]:
    path_2_category = {
        "/mens-clothing-basic-t-shirts/": ProductCategory.TSHIRT.value,
        "/mens-clothing-print-t-shirts/": ProductCategory.TSHIRT.value,
        "/mens-clothing-vests/": ProductCategory.TOP.value,
        "/mens-clothing-polo-shirts/": ProductCategory.SHIRT.value,
        "/mens-clothing-long-sleeve-tops/": ProductCategory.SHIRT.value,
        "/mens-sports-t-shirts/": ProductCategory.TSHIRT.value,
        "/mens-clothing-shirts/": ProductCategory.SHIRT.value,
        "/mens-clothing-jumpers-hoodies/": ProductCategory.SWEATER.value,
        "/mens-sweatshirts/": ProductCategory.SWEATER.value,
        "/mens-athletic-jackets/": ProductCategory.JACKET.value,
        "/mens-fleece-jumpers/": ProductCategory.SWEATER.value,
        "/mens-cardigans/": ProductCategory.JACKET.value,
        "/mens-clothing-jumpers-knitted-jumpers/": ProductCategory.SWEATER.value,
        "/mens-clothing-jackets/": ProductCategory.JACKET.value,
        "/mens-clothing-coats/": ProductCategory.JACKET.value,
        "/mens-clothing-suits/": ProductCategory.SUIT.value,
        "/mens-clothing-suit-jackets/": ProductCategory.JACKET.value,
        "/mens-clothing-suits-business-shirts/": ProductCategory.SHIRT.value,
        "/mens-clothing-suit-trousers/": ProductCategory.PANTS.value,
        "/mens-clothing-suits-waistcoats/": ProductCategory.JACKET.value,
        "/mens-clothing-jackets-suit-jackets/": ProductCategory.JACKET.value,
        "/mens-clothing-jeans/": ProductCategory.JEANS.value,
        "/mens-clothing-trousers/": ProductCategory.PANTS.value,
        "/mens-clothing-shorts/": ProductCategory.SHORTS.value,
        "/mens-clothing-tracksuits-joggers/": ProductCategory.TRACKSUIT.value,
        "/mens-clothing-joggers/": ProductCategory.PANTS.value,
        "/mens-clothing-jackets-athletic-jackets/": ProductCategory.JACKET.value,
        "/mens-clothing-underpants/": ProductCategory.UNDERWEAR.value,
        "/mens-vests/": ProductCategory.UNDERWEAR.value,
        "/mens-clothing-socks/": ProductCategory.SOCKS.value,
        "/mens-clothing-nightwear/": ProductCategory.NIGHTWEAR.value,
        "/swimming-trunks/": ProductCategory.SWIMWEAR.value,
        "/mens-towels/": ProductCategory.TOWEL.value,
        "/bathrobe-men/": ProductCategory.NIGHTWEAR.value,
        "/mens-underwear-dressing-gowns/": ProductCategory.NIGHTWEAR.value,
        "/mens-sports-plain-t-shirts/": (ProductCategory.TSHIRT.value, {"type": "SPORT"}),
        "/mens-sports-tank-tops/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/mens-sports-polo-shirts/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/mens-sports-long-sleeve-tops/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/sports-shirts/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/sports-jerseys-men/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/mens-sports-jackets-gilets/": (ProductCategory.JACKET.value, {"type": "SPORT"}),
        "/mens-sports-shorts-trousers/": (ProductCategory.SHORTS.value, {"type": "SPORT"}),
        "/mens-sports-jumpers-sweatshirts/": (ProductCategory.SWEATER.value, {"type": "SPORT"}),
        "/mens-tracksuits/": (ProductCategory.TRACKSUIT.value, {"type": "SPORT"}),
        "/mens-base-layers/": (ProductCategory.UNDERWEAR.value, {"type": "SPORT"}),
        "/mens-clothing-sports-socks/": (ProductCategory.UNDERWEAR.value, {"type": "SPORT"}),
        "/mens-sports-swimwear/": (ProductCategory.SWIMWEAR.value, {"type": "SPORT"}),
        "/mens-sports-shoes/": (ProductCategory.SHOES.value, {"type": "SPORT"}),
        "/mens-sports-bags-rucksacks/": (ProductCategory.BACKPACK.value, {"type": "SPORT"}),
        "/mens-bags-sports/": (ProductCategory.BAG.value, {"type": "SPORT"}),
        "/mens-shoes-trainers/": ProductCategory.SNEAKERS.value,
        "/mens-shoes-lace-up-shoes/": ProductCategory.SHOES.value,
        "/mens-shoes-flat-shoes/": ProductCategory.SHOES.value,
        "/mens-shoes-business-shoes/": ProductCategory.SHOES.value,
        "/mens-shoes-sandals/": ProductCategory.SHOES.value,
        "/mens-shoes-boots/": ProductCategory.SHOES.value,
        "/mens-shoes-slippers/": ProductCategory.SHOES.value,
        "/mens-shoulder-bags/": ProductCategory.BAG.value,
        "/shopper-mens/": ProductCategory.BAG.value,
        "/mens-laptop-bags/": ProductCategory.BAG.value,
        "/sports-bags-travel-bags-men/": ProductCategory.BAG.value,
        "/mens-rucksacks/": ProductCategory.BACKPACK.value,
        "/small-bags-men/": ProductCategory.BAG.value,
        "/mens-sports-travel-bags/": ProductCategory.BAG.value,
    }

    return combine_results(
        path_2_category,
        gender=GenderType.MALE.value,
        consumer_lifestage=ConsumerLifestageType.ADULT.value,
    )


def female() -> List[dict]:
    path_2_category = {
        "/womens-clothing-dresses/": ProductCategory.DRESS.value,
        "/womens-clothing-tops-t-shirts/": ProductCategory.TSHIRT.value,
        "/womens-clothing-tops-tops/": ProductCategory.TOP.value,
        "/womens-clothing-tops-polo-shirts/": ProductCategory.SHIRT.value,
        "/womens-clothing-tops-long-sleeve-tops/": ProductCategory.SHIRT.value,
        "/womens-clothing-blouses-tunics/": ProductCategory.BLOUSE.value,
        "/womens-clothing-cardigans/": ProductCategory.JACKET.value,
        "/womens-clothing-jumpers/": ProductCategory.SWEATER.value,
        "/womens-clothing-sweatshirts/": ProductCategory.SWEATER.value,
        "/womens-clothing-hoodies/": ProductCategory.SWEATER.value,
        "/womens-clothing-jackets-fleeces/": ProductCategory.JACKET.value,
        "/womens-clothing-fleece-jumpers/": ProductCategory.SWEATER.value,
        "/womens-clothing-jackets/": ProductCategory.JACKET.value,
        "/womens-clothing-coats/": ProductCategory.JACKET.value,
        "/womens-clothing-jeans/": ProductCategory.JEANS.value,
        "/womens-clothing-trousers/": ProductCategory.PANTS.value,
        "/womens-clothing-shorts/": ProductCategory.SHORTS.value,
        "/womens-clothing-playsuits-jumpsuits/": ProductCategory.OVERALL.value,
        "/womens-clothing-skirts/": ProductCategory.SKIRT.value,
        "/womens-clothing-underwear/": ProductCategory.UNDERWEAR.value,
        "/nightwear/": ProductCategory.NIGHTWEAR.value,
        "/tights/": ProductCategory.UNDERWEAR.value,
        "/leggings/": ProductCategory.PANTS.value,
        "/socks/": ProductCategory.SOCKS.value,
        "/sports-socks/": ProductCategory.SOCKS.value,
        "/knee-high-socks/": ProductCategory.SOCKS.value,
        "/thigh-high-socks/": ProductCategory.SOCKS.value,
        "/bikinis/": ProductCategory.SWIMWEAR.value,
        "/swimsuits/": ProductCategory.SWIMWEAR.value,
        "/womens-sports-plain-t-shirts/": (ProductCategory.TSHIRT.value, {"type": "SPORT"}),
        "/womens-sports-polo-shirts/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/womens-sports-tops/": (ProductCategory.TOP.value, {"type": "SPORT"}),
        "/womens-sports-long-sleeve-tops/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/womens-sports-blouses/": (ProductCategory.BLOUSE.value, {"type": "SPORT"}),
        "/sports-women-jerseys/": (ProductCategory.SHIRT.value, {"type": "SPORT"}),
        "/womens-sports-jackets-gilets/": (ProductCategory.JACKET.value, {"type": "SPORT"}),
        "/womens-sports-shorts-trousers/": (ProductCategory.SHORTS.value, {"type": "SPORT"}),
        "/womens-sports-jumpers-sweatshirts/": (ProductCategory.SWEATER.value, {"type": "SPORT"}),
        "/womens-sports-dresses/": (ProductCategory.DRESS.value, {"type": "SPORT"}),
        "/womens-sports-skirts/": (ProductCategory.SKIRT.value, {"type": "SPORT"}),
        "/womens-sports-bras/": (ProductCategory.UNDERWEAR.value, {"type": "SPORT"}),
        "/womens-base-layers/": (ProductCategory.UNDERWEAR.value, {"type": "SPORT"}),
        "/womens-sports-socks/": (ProductCategory.SOCKS.value, {"type": "SPORT"}),
        "/sportsuit-women/": (ProductCategory.TRACKSUIT.value, {"type": "SPORT"}),
        "/gymsuit-leotards-women/": (ProductCategory.OVERALL.value, {"type": "SPORT"}),
        "/womens-sports-swimwear/": (ProductCategory.SWIMWEAR.value, {"type": "SPORT"}),
        "/womens-sports-shoes/": (ProductCategory.SHOES.value, {"type": "SPORT"}),
        "/womens-sports-bags-rucksacks/": (ProductCategory.BACKPACK.value, {"type": "SPORT"}),
        "/womens-sports-bags/": (ProductCategory.BAG.value, {"type": "SPORT"}),
        "/womens-shoes-trainers/": ProductCategory.SNEAKERS.value,
        "/womens-shoes-ankle-boots/": ProductCategory.SHOES.value,
        "/womens-shoes-boots/": ProductCategory.SHOES.value,
        "/womens-shoes-sandals/": ProductCategory.SHOES.value,
        "/womens-shoes-high-heels/": ProductCategory.SHOES.value,
        "/womens-shoes-heels/": ProductCategory.SHOES.value,
        "/womens-shoes-bridal-shoes/": ProductCategory.SHOES.value,
        "/womens-shoes-flats-lace-ups/": ProductCategory.SHOES.value,
        "/womens-shoes-ballet-pumps/": ProductCategory.SHOES.value,
        "/womens-shoes-mules-clogs/": ProductCategory.SHOES.value,
        "/womens-shoes-slippers/": ProductCategory.SHOES.value,
        "/flip-flops-beach-shoes/": ProductCategory.SHOES.value,
        "/handbags/": ProductCategory.BAG.value,
        "/clutch-bags/": ProductCategory.BAG.value,
        "/shopping-bags/": ProductCategory.BAG.value,
        "/shoulder-bags/": ProductCategory.BAG.value,
        "/laptop-bags/": ProductCategory.BAG.value,
        "/wash-bags/": ProductCategory.BAG.value,
        "/bum-bags-women/": ProductCategory.BAG.value,
        "/women-bags-accessories-pencil-case/": ProductCategory.BAG.value,
        "/rucksacks/": ProductCategory.BACKPACK.value,
        "/sports-travel-bags/": ProductCategory.BAG.value,
    }

    return combine_results(
        path_2_category,
        gender=GenderType.FEMALE.value,
        consumer_lifestage=ConsumerLifestageType.ADULT.value,
    )


def get_settings() -> List[dict]:
    return male() + female()
