architecture: standalone
volumePermissions:
  enabled: true
auth:
  existingSecret: redis-secret
  existingSecretPasswordKey: root-password
master:
  resources:
    limits:
      memory: "4Gi"
      cpu: 2
    requests:
      memory: "2Gi"
      cpu: 1
  persistence:
    existingClaim: redis-pvc
  extraEnvVars:
    - name: TZ
      value: Europe/Berlin
