apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-classification.fullname" . }}
  labels:
    {{- include "product-classification.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "product-classification.selectorLabels" . | nindent 4 }}
