from core import log
from core.constants import (
    TABLE_NAME_SCRAPING_AMAZON_DE,
    TABLE_NAME_SCRAPING_ASOS_FR,
    TABLE_NAME_SCRAPING_OTTO_DE,
    TABLE_NAME_SCRAPING_ZALANDO_DE,
    TABLE_NAME_SCRAPING_ZALANDO_FR,
    TABLE_NAME_SCRAPING_ZALANDO_UK,
)
from database.connection import Scraping

log.setup_logger(__name__)

CONNECTION_FOR_TABLE = {
    TABLE_NAME_SCRAPING_AMAZON_DE: Scraping(TABLE_NAME_SCRAPING_AMAZON_DE),
    TABLE_NAME_SCRAPING_ASOS_FR: Scraping(TABLE_NAME_SCRAPING_ASOS_FR),
    TABLE_NAME_SCRAPING_OTTO_DE: Scraping(TABLE_NAME_SCRAPING_OTTO_DE),
    TABLE_NAME_SCRAPING_ZALANDO_DE: Scraping(TABLE_NAME_SCRAPING_ZALANDO_DE),
    TABLE_NAME_SCRAPING_ZALANDO_FR: Scraping(TABLE_NAME_SCRAPING_ZALANDO_FR),
    TABLE_NAME_SCRAPING_ZALANDO_UK: Scraping(TABLE_NAME_SCRAPING_ZALANDO_UK),
}
