# This code is duplicated from workers/workers/__init__.py in order to avoid importing workers
# package and its unneeded dependencies (extract, message queue and redis) to the monitoring
# environment.
from core import log
from core.constants import (
    TABLE_NAME_SCRAPING_AMAZON_DE,
    TABLE_NAME_SCRAPING_AMAZON_FR,
    TABLE_NAME_SCRAPING_AMAZON_GB,
    TABLE_NAME_SCRAPING_ASOS_FR,
    TABLE_NAME_SCRAPING_HM_FR,
    TABLE_NAME_SCRAPING_OTTO_DE,
    TABLE_NAME_SCRAPING_ZALANDO_DE,
    TABLE_NAME_SCRAPING_ZALANDO_FR,
    TABLE_NAME_SCRAPING_ZALANDO_GB,
)
from database.connection import Scraping

log.setup_logger(__name__)

CONNECTION_FOR_TABLE = {
    TABLE_NAME_SCRAPING_AMAZON_DE: Scraping(TABLE_NAME_SCRAPING_AMAZON_DE),
    TABLE_NAME_SCRAPING_AMAZON_FR: Scraping(TABLE_NAME_SCRAPING_AMAZON_FR),
    TABLE_NAME_SCRAPING_AMAZON_GB: Scraping(TABLE_NAME_SCRAPING_AMAZON_GB),
    TABLE_NAME_SCRAPING_ASOS_FR: Scraping(TABLE_NAME_SCRAPING_ASOS_FR),
    TABLE_NAME_SCRAPING_OTTO_DE: Scraping(TABLE_NAME_SCRAPING_OTTO_DE),
    TABLE_NAME_SCRAPING_ZALANDO_DE: Scraping(TABLE_NAME_SCRAPING_ZALANDO_DE),
    TABLE_NAME_SCRAPING_ZALANDO_FR: Scraping(TABLE_NAME_SCRAPING_ZALANDO_FR),
    TABLE_NAME_SCRAPING_ZALANDO_GB: Scraping(TABLE_NAME_SCRAPING_ZALANDO_GB),
    TABLE_NAME_SCRAPING_HM_FR: Scraping(TABLE_NAME_SCRAPING_HM_FR),
}
