volumePermissions:
  enabled: true
primary:
  persistence:
    size: 100Gi
    existingClaim: postgres-pvc
  extraEnvVars:
    - name: TZ
      value: Europe/Berlin
auth:
  existingSecret: postgres-secret
