apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-classification-pod
  namespace: s76866
spec:
  replicas: 1
  selector:
    matchLabels:
      service: product-classification-pod
  strategy:
  template:
    metadata:
      labels:
        service: product-classification-pod
    spec:
      containers:
        - name: product-classification-container
          image: registry.datexis.com/s76866/product-classification:latest
          imagePullPolicy: "Always"
          ports:
            - name: client-port
              containerPort: 8282
          volumeMounts:
            - mountPath: "/usr/src/app/data" # mounting
              name: data
          env:
            - name: TZ
              value: Europe/Berlin
            - name: POSTGRES_GREEN_DB_HOST
              value: postgresql
            - name: POSTGRES_GREEN_DB_PORT
              value: "5432"
            - name: POSTGRES_GREEN_DB_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-user
                  name: green-db-secret
            - name: POSTGRES_GREEN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: green-db-secret
      imagePullSecrets:
        - name: private-registry-auth
      nodeSelector:
        cpuclass: epyc
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: product-classification-pvc