apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-classification-pvc
  namespace: s76866
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared