apiVersion: v1
kind: Pod
metadata:
  name: tool
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: debian
    name: tool
    volumeMounts:
    - mountPath: /cephfs
      name: fsmount
    volumeMounts:
      - mountPath: /data # mounting
        name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: product-classification-pvc