[tool.poetry]
name = "workers"
version = "0.0.0"
description = ""
license = "Apache-2.0"
authors = ["Sebastian Jäger <message@sebastian-jaeger.me>"]
readme = "README.md"
repository = "https://github.com/calgo-lab/green-db"
keywords = ["GreenDB", "database", "scraping", "sustainable", "green"]
classifiers = [
    "Framework :: Scrapy",
    "Topic :: Database"
]

[tool.poetry.scripts]
worker = "workers.main:start"

[tool.poetry.dependencies]
python = "^3.10"
core = {path = "../core", develop = true}
database = {path = "../database", develop = true}
extract = {path = "../extract", develop = true}
message_queue = {path = "../message-queue", develop = true}
redis = "^4.1.1"
rq = "^1.10.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
mypy = "^0.910"
isort = "^5.10.1"
black = "^21.12b0"
types-redis = "^4.1.10"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[tool.mypy]
python_version = 3.10
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100
