# Default values for workers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/calgo-lab/green-db/workers
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

queues: # defined in 'core' package 'constants.py' prefix: 'WORKER_QUEUE_<...>'
  scraping:
    # references `DBEnv`
    - scraping
  extract:
    - scraping
    - greenDb

DBEnv:
  scraping:
    - name: POSTGRES_SCRAPING_HOST
      value: postgresql
    - name: POSTGRES_SCRAPING_PORT
      value: "5432"
    - name: POSTGRES_SCRAPING_USER
      valueFrom:
        secretKeyRef:
          name: scraping-secret
          key: postgres-user
    - name: POSTGRES_SCRAPING_PASSWORD
      valueFrom:
        secretKeyRef:
          name: scraping-secret
          key: postgres-password
  greenDb:
    - name: POSTGRES_GREEN_DB_HOST
      value: postgresql
    - name: POSTGRES_GREEN_DB_PORT
      value: "5432"
    - name: POSTGRES_GREEN_DB_USER
      valueFrom:
        secretKeyRef:
          name: green-db-secret
          key: postgres-user
    - name: POSTGRES_GREEN_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: green-db-secret
          key: postgres-password

env:
  - name: TZ
    value: Europe/Berlin
  - name: REDIS_HOST
    value: redis-master
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: root-password

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2
    memory: 512Mi
  requests:
    cpu: 2
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
