name: Lint

on:
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          MATCHERS=.github/workflows/matchers/*.json
          echo $MATCHERS

          for matcher in $MATCHERS
          do
              echo adding matcher $matcher
              echo "::add-matcher::${matcher}"
          done

          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install black
      - name: Run black
        run: |
          black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          MATCHERS=.github/workflows/matchers/*.json
          echo $MATCHERS

          for matcher in $MATCHERS
          do
              echo adding matcher $matcher
              echo "::add-matcher::${matcher}"
          done

          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install isort
      - name: Run isort
        run: |
          isort  -c --diff .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          MATCHERS=.github/workflows/matchers/*.json
          echo $MATCHERS

          for matcher in $MATCHERS
          do
              echo adding matcher $matcher
              echo "::add-matcher::${matcher}"
          done

          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup Matchers
        run: |
          MATCHERS=.github/workflows/matchers/*.json
          echo $MATCHERS

          for matcher in $MATCHERS
          do
              echo adding matcher $matcher
              echo "::add-matcher::${matcher}"
          done

          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install mypy types-redis types-requests
      - name: Run mypy
        run: |
          mypy --show-column-numbers .
